.TH Animal 6l
.SH NAME
Animal \- the classic game of animal
.SH SYNOPSIS
.B animal
.B [database]
.SH DESCRIPTION
.I Animal
is an implementation of the ``guess the animal'' game,
an assignment given to most first year computer science students.
This version uses curses(3X) to give a reasonable interface,
and can read and save a database of questions and objects.
.PP
The basic idea of the game is to think of an object
then answer ``yes or no'' questions
until the program has a final guess at what you are thinking
of.  If it is correct then you will be convinced that there
may be something to AI after all.  If it is incorrect you are
expected to provide a question that, when asked, will yeild
a yes or no answer that will allow the computer to distinguish
between its last guess and the correct object. For example if
its last guess is Ronald Reagan but you were thinking of a gnat,
then a suitable question would be 'Is it an insect?'.  For RR
the answer would be no, for a gnat the answer would be yes.
.PP
Hints on choosing good questions: 
(a) keep the questions as general as possible,
(b) never explicitly refer to either of the objects in your question, and
(c) all questions can only have a yes or no answer, so avoid questions
that could produce a ``maybe'' answer.
.PP
At the end of the game you will be asked if you want to save
the information you have added.  A text file with a name
of your choosing will be created, and can be used as an argument
for later invocations of
.I animal.
.SH BUGS
Unknown, but please send bug problems to {utzoo,utcsri,lsuc}!hcr!stacey.
.SH AUTHOR
Stacey Campbell \- HCR Corporation, Toronto, Canada, 1989.
.SH DISCLAIMER
Animal is copyright 1989 by HCR Corporation, Toronto, Ontario, Canada.
Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies.
.PP
HCR  Corporation  disclaims all  warranties with regard to
this software. Use at your own risk.
